version: "3.8"

services:
  fastapi-service:
    build: .
    container_name: fastapi-baseline
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
    env_file:  # Указываем путь к .env файлу
      - .env
    volumes:
      - ./logs:/app/logs
    # Если нужно GPU
    # runtime: nvidia
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
